import React, { createContext, useContext, useState, useEffect } from 'react';

export interface LanguageOption {
  code: string;
  name: string;
  native: string;
  flag: string;
  greeting: string;
  dir?: 'ltr' | 'rtl';
}

export const AVAILABLE_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', native: 'English', flag: '🇬🇧', greeting: 'Hello' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी', flag: '🇮🇳', greeting: 'नमस्ते' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు', flag: '🇮🇳', greeting: 'నమస్కారం' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்', flag: '🇮🇳', greeting: 'வணக்கம்' },
  { code: 'es', name: 'Spanish', native: 'Español', flag: '🇪🇸', greeting: 'Hola' },
  { code: 'fr', name: 'French', native: 'Français', flag: '🇫🇷', greeting: 'Bonjour' },
  { code: 'ar', name: 'Arabic', native: 'العربية', flag: '🇸🇦', greeting: 'مرحبا', dir: 'rtl' },
  { code: 'de', name: 'German', native: 'Deutsch', flag: '🇩🇪', greeting: 'Hallo' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা', flag: '🇮🇳', greeting: 'নমস্কার' },
  { code: 'mr', name: 'Marathi', native: 'मराठी', flag: '🇮🇳', greeting: 'नमस्कार' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ', flag: '🇮🇳', greeting: 'ನಮಸ್ಕಾರ' },
  { code: 'ml', name: 'Malayalam', native: 'മലയാളം', flag: '🇮🇳', greeting: 'നമസ്കാരം' },
];

export type TranslationKey =
  | 'appName'
  | 'appSubtitle'
  | 'liveMode'
  | 'bookAppointment'
  | 'notifications'
  | 'signOut'
  | 'patient'
  | 'doctor'
  | 'admin'
  | 'patientRavi'
  | 'doctorRamesh'
  | 'hospitalAdmin'
  | 'switchActiveRole'
  // Bottom Nav
  | 'navHome'
  | 'navAppointments'
  | 'navTracker'
  | 'navProfile'
  // Patient Portal
  | 'patientPortal'
  | 'greeting'
  | 'queueSummary'
  | 'hospitalStatus'
  | 'refresh'
  | 'bookNew'
  | 'activeTicket'
  | 'yourToken'
  | 'inQueue'
  | 'nextInLine'
  | 'consultationActive'
  | 'doctorLabel'
  | 'appointmentDate'
  | 'estimatedWait'
  | 'peopleAhead'
  | 'openLiveTracker'
  | 'liveQueueStatus'
  | 'token'
  | 'patientName'
  | 'department'
  | 'waitTime'
  | 'status'
  | 'completed'
  | 'current'
  | 'upcoming'
  | 'mins'
  | 'today'
  | 'pastRecords'
  | 'verifiedId'
  | 'contactPhone'
  | 'ageGender'
  | 'bloodGroup'
  | 'hospitalBranch'
  // Live Queue Tracker
  | 'liveQueueTitle'
  | 'selectDept'
  | 'currentToken'
  | 'nowConsulting'
  | 'waitMessage'
  | 'queueProgress'
  | 'tokenGenerated'
  | 'almostYourTurn'
  | 'yourTurn'
  | 'refreshStatus'
  | 'autoRefreshOn'
  | 'patientsWaiting'
  // Appointment Booking Modal
  | 'bookDoctorVisit'
  | 'step'
  | 'selectDoctor'
  | 'selectDate'
  | 'selectTime'
  | 'confirmBooking'
  | 'continueBtn'
  | 'backBtn'
  | 'bookingSuccess'
  | 'tokenGeneratedNotice'
  | 'close'
  // Settings / Profile
  | 'settingsTitle'
  | 'settingsSubtitle'
  | 'selectLang'
  | 'chooseLangDesc'
  | 'queueAlerts'
  | 'voiceAnnounce'
  | 'voiceDesc'
  | 'smsAlerts'
  | 'smsDesc'
  | 'seniorMode'
  | 'seniorDesc'
  | 'emergencyContact'
  | 'emergency247'
  | 'dialHelp'
  // Login
  | 'smartQueueSys'
  | 'selectLoginRole'
  | 'loginAs'
  | 'signUp'
  | 'skipForNow'
  | 'useDemoCredentials'
  | 'orTypeCustom'
  // Doctor & Admin
  | 'onDuty'
  | 'todayQueue'
  | 'completedConsultations'
  | 'currentPatient'
  | 'callNext'
  | 'completeConsultation'
  | 'hospitalOverview'
  | 'todayAppointments'
  | 'avgWait'
  | 'liveHospitalQueue'
  | 'dashboard'
  | 'appointments'
  | 'queueTab'
  | 'doctorsTab'
  | 'analyticsTab'
  | 'settingsTab'
  | 'backToDashboard'
  | 'liveQueueTracking'
  | 'liveBroadcast'
  | 'currentConsulting'
  | 'stepDept'
  | 'stepDoctor'
  | 'stepDate'
  | 'stepTime'
  | 'stepConfirm'
  | 'appointmentConfirmed'
  | 'back'
  | 'continue'
  | 'confirmAppointment'
  | 'viewInQueueTracker'
  | 'markAllAsRead';

const TRANSLATIONS: Record<string, Partial<Record<TranslationKey, string>>> = {
  en: {
    appName: 'QuickCare',
    appSubtitle: 'Smart Hospital Queue Management System',
    liveMode: 'QuickCare Live Mode',
    bookAppointment: 'Book Appointment',
    notifications: 'Notifications',
    signOut: 'Sign Out',
    patient: 'Patient',
    doctor: 'Doctor',
    admin: 'Hospital Admin',
    patientRavi: 'Patient (Ravi)',
    doctorRamesh: 'Doctor (Dr. Ramesh)',
    hospitalAdmin: 'Hospital Admin',
    switchActiveRole: 'Switch Active Role',
    navHome: 'Home',
    navAppointments: 'Appointments',
    navTracker: 'Queue Tracker',
    navProfile: 'Profile',
    patientPortal: 'Patient Portal',
    greeting: 'Hello',
    queueSummary: 'Your Queue Summary',
    hospitalStatus: 'Live hospital admission status',
    refresh: 'Refresh',
    bookNew: 'Book New',
    activeTicket: 'ACTIVE QUEUE TICKET',
    yourToken: 'Your Token',
    inQueue: 'In Queue',
    nextInLine: 'Next in Line',
    consultationActive: 'Consultation Active',
    doctorLabel: 'Doctor',
    appointmentDate: 'Appointment Date',
    estimatedWait: 'Estimated Wait Time',
    peopleAhead: 'People Ahead',
    openLiveTracker: 'Open Dedicated Live Tracker',
    liveQueueStatus: 'Live Queue Status',
    token: 'Token',
    patientName: 'Patient Name',
    department: 'Department',
    waitTime: 'Wait Time',
    status: 'Status',
    completed: 'Completed',
    current: 'Current',
    upcoming: 'Upcoming',
    mins: 'mins',
    today: 'Today',
    pastRecords: 'Past Consultation Records',
    verifiedId: 'Verified QuickCare Patient ID',
    contactPhone: 'Contact Phone',
    ageGender: 'Age & Gender',
    bloodGroup: 'Blood Group',
    hospitalBranch: 'Preferred Hospital Branch',
    liveQueueTitle: 'Live Queue Tracking',
    selectDept: 'Select Department',
    currentToken: 'Current Token',
    nowConsulting: 'NOW CONSULTING',
    waitMessage: 'Please wait, your turn is coming soon.',
    queueProgress: 'Queue Progress',
    tokenGenerated: 'Token Generated',
    almostYourTurn: 'Almost Your Turn',
    yourTurn: 'Your Turn',
    refreshStatus: 'Refresh Status',
    autoRefreshOn: 'Live auto-refresh enabled',
    patientsWaiting: 'Patients Waiting',
    bookDoctorVisit: 'Book Doctor Appointment',
    step: 'Step',
    selectDoctor: 'Select Doctor',
    selectDate: 'Select Date',
    selectTime: 'Select Time Slot',
    confirmBooking: 'Confirm Appointment',
    continueBtn: 'Continue',
    backBtn: 'Back',
    bookingSuccess: 'Appointment Confirmed!',
    tokenGeneratedNotice: 'Your digital queue token has been generated',
    close: 'Close',
    settingsTitle: 'Settings & Preferences',
    settingsSubtitle: 'Language, voice chime & accessibility options',
    selectLang: 'Select Application Language',
    chooseLangDesc: 'Choose your preferred language for token tracking, hospital queue status announcements, and consultation alerts:',
    queueAlerts: 'Queue Audio & Alert Settings',
    voiceAnnounce: 'Queue Voice Announcements',
    voiceDesc: 'Audio chime when token number moves ahead',
    smsAlerts: 'SMS / WhatsApp Live Updates',
    smsDesc: 'Receive token arrival reminder when 2 people ahead',
    seniorMode: 'High Contrast / Senior Mode',
    seniorDesc: 'Enlarged token display for easy hospital corridor visibility',
    emergencyContact: 'Hospital Emergency Helpdesk',
    emergency247: 'Available 24/7 for urgent clinical care',
    dialHelp: 'Dial 108 / 911',
    smartQueueSys: 'Smart Hospital Queue Management System',
    selectLoginRole: 'Select Login Role:',
    loginAs: 'Login as',
    signUp: 'Sign Up',
    skipForNow: 'Skip for now',
    useDemoCredentials: 'Use 1-click Demo credentials',
    orTypeCustom: 'Or type custom email & password',
    onDuty: 'On Duty',
    todayQueue: "Today's In-Queue",
    completedConsultations: 'Completed Consultations',
    currentPatient: 'Current Patient in Consultation',
    callNext: 'Call Next Patient',
    completeConsultation: 'Complete Consultation',
    hospitalOverview: 'Hospital Operations Overview',
    todayAppointments: "Today's Appointments",
    avgWait: 'Average Wait Time',
    liveHospitalQueue: 'Live Hospital Queue',
  },
  hi: {
    appName: 'क्विककेयर',
    appSubtitle: 'स्मार्ट अस्पताल कतार प्रबंधन प्रणाली',
    liveMode: 'क्विककेयर लाइव मोड',
    bookAppointment: 'अपॉइंटमेंट बुक करें',
    notifications: 'सूचनाएं',
    signOut: 'साइन आउट',
    patient: 'मरीज़',
    doctor: 'डॉक्टर',
    admin: 'अस्पताल व्यवस्थापक',
    patientRavi: 'मरीज़ (रवि)',
    doctorRamesh: 'डॉक्टर (डॉ. रमेश)',
    hospitalAdmin: 'अस्पताल एडमिन',
    switchActiveRole: 'सक्रिय भूमिका बदलें',
    navHome: 'होम',
    navAppointments: 'अपॉइंटमेंट',
    navTracker: 'कतार ट्रैकर',
    navProfile: 'प्रोफ़ाइल',
    patientPortal: 'रोगी पोर्टल',
    greeting: 'नमस्ते',
    queueSummary: 'आपकी कतार का सारांश',
    hospitalStatus: 'अस्पताल की लाइव कतार स्थिति',
    refresh: 'ताज़ा करें',
    bookNew: 'नया बुक करें',
    activeTicket: 'सक्रिय कतार टोकन',
    yourToken: 'आपका टोकन',
    inQueue: 'कतार में',
    nextInLine: 'कतार में अगला',
    consultationActive: 'परामर्श चालू है',
    doctorLabel: 'डॉक्टर',
    appointmentDate: 'अपॉइंटमेंट दिनांक',
    estimatedWait: 'अनुमानित प्रतीक्षा समय',
    peopleAhead: 'आगे कतार में लोग',
    openLiveTracker: 'लाइव कतार ट्रैकर खोलें',
    liveQueueStatus: 'लाइव कतार स्थिति',
    token: 'टोकन',
    patientName: 'मरीज़ का नाम',
    department: 'विभाग',
    waitTime: 'प्रतीक्षा समय',
    status: 'स्थिति',
    completed: 'पूर्ण हुआ',
    current: 'वर्तमान',
    upcoming: 'आगामी',
    mins: 'मिनट',
    today: 'आज',
    pastRecords: 'पिछले परामर्श रिकॉर्ड',
    verifiedId: 'सत्यापित क्विककेयर रोगी आईडी',
    contactPhone: 'संपर्क फोन',
    ageGender: 'आयु और लिंग',
    bloodGroup: 'रक्त समूह',
    hospitalBranch: 'पसंदीदा अस्पताल शाखा',
    liveQueueTitle: 'लाइव कतार ट्रैकिंग',
    selectDept: 'विभाग चुनें',
    currentToken: 'वर्तमान टोकन',
    nowConsulting: 'परामर्श चल रहा है',
    waitMessage: 'कृपया प्रतीक्षा करें, आपकी बारी जल्द आ रही है।',
    queueProgress: 'कतार की प्रगति',
    tokenGenerated: 'टोकन जनरेट हुआ',
    almostYourTurn: 'लगभग आपकी बारी',
    yourTurn: 'आपकी बारी',
    refreshStatus: 'स्थिति ताज़ा करें',
    autoRefreshOn: 'लाइव ऑटो-रिफ्रेश सक्रिय',
    patientsWaiting: 'प्रतीक्षारत मरीज',
    bookDoctorVisit: 'डॉक्टर अपॉइंटमेंट बुक करें',
    step: 'चरण',
    selectDoctor: 'डॉक्टर चुनें',
    selectDate: 'दिनांक चुनें',
    selectTime: 'समय चुनें',
    confirmBooking: 'अपॉइंटमेंट की पुष्टि करें',
    continueBtn: 'आगे बढ़ें',
    backBtn: 'पीछे जाएं',
    bookingSuccess: 'अपॉइंटमेंट की पुष्टि हो गई!',
    tokenGeneratedNotice: 'आपका डिजिटल कतार टोकन तैयार कर दिया गया है',
    close: 'बंद करें',
    settingsTitle: 'सेटिंग्स और प्राथमिकताएं',
    settingsSubtitle: 'भाषा, वॉयस चाइम और पहुंच विकल्प',
    selectLang: 'आवेदन की भाषा चुनें',
    chooseLangDesc: 'टोकन ट्रैकिंग और अस्पताल कतार स्थिति के लिए अपनी पसंदीदा भाषा चुनें:',
    queueAlerts: 'कतार ऑडियो और चेतावनी सेटिंग्स',
    voiceAnnounce: 'कतार ध्वनि घोषणा',
    voiceDesc: 'टोकन नंबर आगे बढ़ने पर ऑडियो घंटी',
    smsAlerts: 'एसएमएस / व्हाट्सएप लाइव अपडेट',
    smsDesc: 'जब आपके आगे 2 मरीज हों तो सूचना प्राप्त करें',
    seniorMode: 'उच्च कंट्रास्ट / वरिष्ठ मोड',
    seniorDesc: 'सुगम दृश्यता के लिए बड़ा टोकन डिस्प्ले',
    emergencyContact: 'अस्पताल आपातकालीन सहायता डेस्क',
    emergency247: 'आपातकालीन चिकित्सा के लिए 24/7 उपलब्ध',
    dialHelp: 'डायल 108 / 911',
    smartQueueSys: 'स्मार्ट अस्पताल कतार प्रबंधन प्रणाली',
    selectLoginRole: 'लॉगिन भूमिका चुनें:',
    loginAs: 'के रूप में लॉगिन करें',
    signUp: 'साइन अप करें',
    skipForNow: 'अभी छोड़ें',
    useDemoCredentials: '1-क्लिक डेमो क्रेडेंशियल उपयोग करें',
    orTypeCustom: 'या कस्टम ईमेल और पासवर्ड दर्ज करें',
    onDuty: 'ड्यूटी पर',
    todayQueue: 'आज की कतार',
    completedConsultations: 'पूर्ण परामर्श',
    currentPatient: 'वर्तमान परामर्श मरीज',
    callNext: 'अगले मरीज को बुलाएं',
    completeConsultation: 'परामर्श पूरा करें',
    hospitalOverview: 'अस्पताल संचालन अवलोकन',
    todayAppointments: 'आज के अपॉइंटमेंट',
    avgWait: 'औसत प्रतीक्षा समय',
    liveHospitalQueue: 'लाइव अस्पताल कतार',
  },
  te: {
    appName: 'క్విక్‌కేర్',
    appSubtitle: 'స్మార్ట్ హాస్పిటల్ క్యూ నిర్వహణ వ్యవస్థ',
    liveMode: 'క్విక్‌కేర్ లైవ్ మోడ్',
    bookAppointment: 'అపాయింట్‌మెంట్ బుక్ చేయండి',
    notifications: 'నోటిఫికేషన్లు',
    signOut: 'సైన్ అవుట్',
    patient: 'రోగి',
    doctor: 'వైద్యుడు',
    admin: 'హాస్పిటల్ అడ్మిన్',
    patientRavi: 'రోగి (రవి)',
    doctorRamesh: 'డాక్టర్ (డా. రమేష్)',
    hospitalAdmin: 'హాస్పిటల్ అడ్మిన్',
    switchActiveRole: 'క్రియాశీల పాత్రను మార్చండి',
    navHome: 'హోమ్',
    navAppointments: 'అపాయింట్‌మెంట్లు',
    navTracker: 'క్యూ ట్రాకర్',
    navProfile: 'ప్రొఫైల్',
    patientPortal: 'రోగుల పోర్టల్',
    greeting: 'నమస్కారం',
    queueSummary: 'మీ క్యూ వివరాలు',
    hospitalStatus: 'ప్రత్యక్ష ఆసుపత్రి స్థితి',
    refresh: 'రీఫ్రెష్ చేయండి',
    bookNew: 'కొత్తది బుక్ చేయండి',
    activeTicket: 'యాక్టివ్ క్యూ టోకెన్',
    yourToken: 'మీ టోకెన్',
    inQueue: 'క్యూలో ఉంది',
    nextInLine: 'తదుపరి వరుసలో',
    consultationActive: 'సంప్రదింపు నడుస్తోంది',
    doctorLabel: 'డాక్టర్',
    appointmentDate: 'అపాయింట్‌మెంట్ తేదీ',
    estimatedWait: 'అంచనా వేసిన వేచి ఉండే సమయం',
    peopleAhead: 'మీకు ముందు ఉన్నవారు',
    openLiveTracker: 'లైవ్ ట్రాకర్ తెరవండి',
    liveQueueStatus: 'లైవ్ క్యూ స్థితి',
    token: 'టోకెన్',
    patientName: 'రోగి పేరు',
    department: 'విభాగం',
    waitTime: 'వేచి ఉండే సమయం',
    status: 'స్థితి',
    completed: 'పూర్తయింది',
    current: 'ప్రస్తుతం',
    upcoming: 'రాబోయేది',
    mins: 'నిమిషాలు',
    today: 'ఈ రోజు',
    pastRecords: 'మునుపటి సంప్రదింపు రికార్డులు',
    verifiedId: 'ధృవీకరించబడిన క్విక్‌కేర్ రోగి ఐడి',
    contactPhone: 'ఫోన్ నంబర్',
    ageGender: 'వయస్సు & లింగం',
    bloodGroup: 'రక్త వర్గం',
    hospitalBranch: 'ఆసుపత్రి శాఖ',
    liveQueueTitle: 'ప్రత్యక్ష క్యూ ట్రాకింగ్',
    selectDept: 'విభాగాన్ని ఎంచుకోండి',
    currentToken: 'ప్రస్తుత టోకెన్',
    nowConsulting: 'ఇప్పుడు సంప్రదింపు జరుగుతోంది',
    waitMessage: 'దయచేసి వేచి ఉండండి, మీ వంతు త్వరలో వస్తుంది.',
    queueProgress: 'క్యూ పురోగతి',
    tokenGenerated: 'టోకెన్ రూపొందించబడింది',
    almostYourTurn: 'మీ వంతు రాబోతోంది',
    yourTurn: 'మీ వంతు వచ్చింది',
    refreshStatus: 'స్థితిని రిఫ్రెష్ చేయండి',
    autoRefreshOn: 'ఆటో-రిఫ్రెష్ ఆన్‌లో ఉంది',
    patientsWaiting: 'వేచి ఉన్న రోగులు',
    bookDoctorVisit: 'డాక్టర్ అపాయింట్‌మెంట్ బుక్ చేయండి',
    step: 'దశ',
    selectDoctor: 'డాక్టర్‌ను ఎంచుకోండి',
    selectDate: 'తేదీని ఎంచుకోండి',
    selectTime: 'సమయాన్ని ఎంచుకోండి',
    confirmBooking: 'అపాయింట్‌మెంట్‌ని నిర్ధారించండి',
    continueBtn: 'కొనసాగించండి',
    backBtn: 'వెనుకకు',
    bookingSuccess: 'అపాయింట్‌మెంట్ ధృవీకరించబడింది!',
    tokenGeneratedNotice: 'మీ డిజిటల్ క్యూ టోకెన్ రూపొందించబడింది',
    close: 'మూసివేయి',
    settingsTitle: 'సెట్టింగ్‌లు & ప్రాధాన్యతలు',
    settingsSubtitle: 'భాష, వాయిస్ చైమ్ మరియు ఇతర ఎంపికలు',
    selectLang: 'అనువర్తన భాషను ఎంచుకోండి',
    chooseLangDesc: 'టోకెన్ ట్రాకింగ్ మరియు ఆసుపత్రి క్యూ సమాచారం కోసం మీ భాషను ఎంచుకోండి:',
    queueAlerts: 'ఆడియో & హెచ్చరిక సెట్టింగ్‌లు',
    voiceAnnounce: 'క్యూ వాయిస్ ప్రకటనలు',
    voiceDesc: 'టోకెన్ ముందుకు కదిలినప్పుడు చైమ్ మోగుతుంది',
    smsAlerts: 'ఎస్ఎంఎస్ / వాట్సాప్ అప్‌డేట్లు',
    smsDesc: 'మీకు ముందు 2 మంది ఉన్నప్పుడు సమాచారం అందుతుంది',
    seniorMode: 'హై కాంట్రాస్ట్ / సీనియర్ మోడ్',
    seniorDesc: 'సులభమైన వీక్షణ కోసం పెద్ద టోకెన్ డిస్ప్లే',
    emergencyContact: 'హాస్పిటల్ అత్యవసర హెల్ప్‌డెస్క్',
    emergency247: 'అత్యవసర సంరక్షణ కోసం 24/7 అందుబాటులో ఉంది',
    dialHelp: 'డయల్ 108 / 911',
    smartQueueSys: 'స్మార్ట్ హాస్పిటల్ క్యూ నిర్వహణ వ్యవస్థ',
    selectLoginRole: 'లాగిన్ పాత్రను ఎంచుకోండి:',
    loginAs: 'గా లాగిన్ అవ్వండి',
    signUp: 'సైన్ అప్',
    skipForNow: 'ఇప్పుడు దాటవేయి',
    useDemoCredentials: '1-క్లిక్ డెమో వివరాలు ఉపయోగించండి',
    orTypeCustom: 'లేదా ఇమెయిల్ & పాస్‌వర్డ్ నమోదు చేయండి',
    onDuty: 'విధులపై ఉన్నారు',
    todayQueue: 'నేటి క్యూ',
    completedConsultations: 'పూర్తయిన సంప్రదింపులు',
    currentPatient: 'ప్రస్తుత రోగి సంప్రదింపు',
    callNext: 'తదుపరి రోగిని పిలవండి',
    completeConsultation: 'సంప్రదింపును పూర్తి చేయండి',
    hospitalOverview: 'ఆసుపత్రి కార్యకలాపాల సమీక్ష',
    todayAppointments: 'నేటి అపాయింట్‌మెంట్లు',
    avgWait: 'సగటు వేచి ఉండే సమయం',
    liveHospitalQueue: 'లైవ్ హాస్పిటల్ క్యూ',
  },
  ta: {
    appName: 'குவிக்கேர்',
    appSubtitle: 'ஸ்மார்ட் மருத்துவமனை வரிசை மேலாண்மை அமைப்பு',
    liveMode: 'குவிக்கேர் நேரலை முறை',
    bookAppointment: 'முன்பதிவு செய்யுங்கள்',
    notifications: 'அறிவிப்புகள்',
    signOut: 'வெளியேறு',
    patient: 'நோயாளி',
    doctor: 'மருத்துவர்',
    admin: 'நிர்வாகி',
    patientRavi: 'நோயாளி (ரவி)',
    doctorRamesh: 'மருத்துவர் (டாக்டர் ரமேஷ்)',
    hospitalAdmin: 'மருத்துவமனை நிர்வாகி',
    switchActiveRole: 'பணியை மாற்றவும்',
    navHome: 'முகப்பு',
    navAppointments: 'முன்பதிவுகள்',
    navTracker: 'வரிசை டிராக்கர்',
    navProfile: 'சுயவிவரம்',
    patientPortal: 'நோயாளி தளம்',
    greeting: 'வணக்கம்',
    queueSummary: 'உங்கள் வரிசை சுருக்கம்',
    hospitalStatus: 'நேரலை மருத்துவமனை நிலை',
    refresh: 'புதுப்பிக்கவும்',
    bookNew: 'புதிதாக முன்பதிவு செய்க',
    activeTicket: 'செயலில் உள்ள டோக்கன்',
    yourToken: 'உங்கள் டோக்கன்',
    inQueue: 'வரிசையில்',
    nextInLine: 'அடுத்த வரிசையில்',
    consultationActive: 'ஆலோசனை நடக்கிறது',
    doctorLabel: 'மருத்துவர்',
    appointmentDate: 'முன்பதிவு தேதி',
    estimatedWait: 'எதிர்பார்க்கப்படும் காத்திருப்பு நேரம்',
    peopleAhead: 'முன்னால் உள்ளவர்கள்',
    openLiveTracker: 'நேரலை டிராக்கரைத் திறக்கவும்',
    liveQueueStatus: 'நேரலை வரிசை நிலை',
    token: 'டோக்கன்',
    patientName: 'நோயாளி பெயர்',
    department: 'துறை',
    waitTime: 'காத்திருப்பு நேரம்',
    status: 'நிலை',
    completed: 'முடிந்தது',
    current: 'தற்போதைய',
    upcoming: 'வரவிருக்கும்',
    mins: 'நிமிடங்கள்',
    today: 'இன்று',
    pastRecords: 'முந்தைய மருத்துவப் பதிவுகள்',
    verifiedId: 'சரிபார்க்கப்பட்ட நோயாளி ஐடி',
    contactPhone: 'தொலைபேசி எண்',
    ageGender: 'வயது & பாலினம்',
    bloodGroup: 'இரத்த வகை',
    hospitalBranch: 'மருத்துவமனை கிளை',
    liveQueueTitle: 'நேரலை வரிசை கண்காணிப்பு',
    selectDept: 'துறையைத் தேர்ந்தெடுக்கவும்',
    currentToken: 'தற்போதைய டோக்கன்',
    nowConsulting: 'இப்போது ஆலோசனை நடக்கிறது',
    waitMessage: 'தயவுசெய்து காத்திருக்கவும், உங்கள் முறை விரைவில் வரும்.',
    queueProgress: 'வரிசை முன்னேற்றம்',
    tokenGenerated: 'டோக்கன் உருவாக்கப்பட்டது',
    almostYourTurn: 'கிட்டத்தட்ட உங்கள் முறை',
    yourTurn: 'உங்கள் முறை வந்தது',
    refreshStatus: 'நிலையைப் புதுப்பிக்கவும்',
    autoRefreshOn: 'தானியங்கி புதுப்பிப்பு இயக்கத்தில் உள்ளது',
    patientsWaiting: 'காத்திருக்கும் நோயாளிகள்',
    bookDoctorVisit: 'மருத்துவரை முன்பதிவு செய்க',
    step: 'படி',
    selectDoctor: 'மருத்துவரைத் தேர்ந்தெடுக்கவும்',
    selectDate: 'தேதியைத் தேர்ந்தெடுக்கவும்',
    selectTime: 'நேரத்தைத் தேர்ந்தெடுக்கவும்',
    confirmBooking: 'முன்பதிவை உறுதி செய்க',
    continueBtn: 'தொடரவும்',
    backBtn: 'பின்செல்',
    bookingSuccess: 'முன்பதிவு உறுதி செய்யப்பட்டது!',
    tokenGeneratedNotice: 'உங்கள் டிஜிட்டல் டோக்கன் உருவாக்கப்பட்டது',
    close: 'மூடு',
    settingsTitle: 'அமைப்புகள் & விருப்பங்கள்',
    settingsSubtitle: 'மொழி, குரல் மணி & அணுகல் விருப்பங்கள்',
    selectLang: 'பயன்பாட்டு மொழியைத் தேர்ந்தெடுக்கவும்',
    chooseLangDesc: 'டோக்கன் கண்காணிப்பு மற்றும் மருத்துவமனை வரிசைக்கு விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்:',
    queueAlerts: 'வரிசை ஒலி & எச்சரிக்கை அமைப்புகள்',
    voiceAnnounce: 'வரிசை குரல் அறிவிப்புகள்',
    voiceDesc: 'டோக்கன் முன்னேறும்போது ஒலி எழுப்பும்',
    smsAlerts: 'எஸ்எம்எஸ் / வாட்ஸ்அப் அறிவிப்புகள்',
    smsDesc: '2 பேர் முன்னால் இருக்கும்போது நினைவூட்டல் கிடைக்கும்',
    seniorMode: 'உயர் மாறுபாடு / மூத்தோர் பயன்முறை',
    seniorDesc: 'எளிதான பார்வைக்கு பெரிய டோக்கன் காட்சி',
    emergencyContact: 'மருத்துவமனை அவசர உதவி மையம்',
    emergency247: 'அவசர சிகிச்சைக்காக 24/7 கிடைக்கும்',
    dialHelp: 'அழைக்கவும் 108 / 911',
    smartQueueSys: 'ஸ்மார்ட் மருத்துவமனை வரிசை மேலாண்மை அமைப்பு',
    selectLoginRole: 'உள்நுழைவு பாத்திரத்தைத் தேர்ந்தெடுக்கவும்:',
    loginAs: 'ஆக உள்நுழைக',
    signUp: 'பதிவு செய்க',
    skipForNow: 'இப்போதைக்கு தவிர்',
    useDemoCredentials: 'டெமோ விவரங்களைப் பயன்படுத்துக',
    orTypeCustom: 'அல்லது மின்னஞ்சல் & கடவுச்சொல்லை உள்ளிடவும்',
    onDuty: 'பணியில் உள்ளார்',
    todayQueue: 'இன்றைய வரிசை',
    completedConsultations: 'முடிந்த ஆலோசனைகள்',
    currentPatient: 'தற்போதைய நோயாளி',
    callNext: 'அடுத்த நோயாளியை அழைக்கவும்',
    completeConsultation: 'ஆலோசனையை முடிக்கவும்',
    hospitalOverview: 'மருத்துவமனை செயல்பாடுகள்',
    todayAppointments: 'இன்றைய முன்பதிவுகள்',
    avgWait: 'சராசரி காத்திருப்பு நேரம்',
    liveHospitalQueue: 'நேரலை வரிசை',
  },
  es: {
    appName: 'QuickCare',
    appSubtitle: 'Sistema Inteligente de Gestión de Filas Hospitalarias',
    liveMode: 'Modo en Vivo QuickCare',
    bookAppointment: 'Reservar Cita',
    notifications: 'Notificaciones',
    signOut: 'Cerrar Sesión',
    patient: 'Paciente',
    doctor: 'Médico',
    admin: 'Administrador',
    patientRavi: 'Paciente (Ravi)',
    doctorRamesh: 'Médico (Dr. Ramesh)',
    hospitalAdmin: 'Admin del Hospital',
    switchActiveRole: 'Cambiar Rol Activo',
    navHome: 'Inicio',
    navAppointments: 'Citas',
    navTracker: 'Fila en Vivo',
    navProfile: 'Perfil',
    patientPortal: 'Portal del Paciente',
    greeting: 'Hola',
    queueSummary: 'Resumen de su Turno',
    hospitalStatus: 'Estado de admisión hospitalaria en vivo',
    refresh: 'Actualizar',
    bookNew: 'Nueva Cita',
    activeTicket: 'TICKET DE FILA ACTIVO',
    yourToken: 'Su Turno',
    inQueue: 'En Fila',
    nextInLine: 'Siguiente en Turno',
    consultationActive: 'Consulta Activa',
    doctorLabel: 'Médico',
    appointmentDate: 'Fecha de la Cita',
    estimatedWait: 'Tiempo de Espera Estimado',
    peopleAhead: 'Personas Adelante',
    openLiveTracker: 'Abrir Rastreador en Vivo',
    liveQueueStatus: 'Estado de la Fila en Vivo',
    token: 'Turno',
    patientName: 'Nombre del Paciente',
    department: 'Departamento',
    waitTime: 'Tiempo de Espera',
    status: 'Estado',
    completed: 'Completado',
    current: 'Actual',
    upcoming: 'Próximo',
    mins: 'min',
    today: 'Hoy',
    pastRecords: 'Historial de Consultas',
    verifiedId: 'ID Verificado del Paciente',
    contactPhone: 'Teléfono de Contacto',
    ageGender: 'Edad y Género',
    bloodGroup: 'Grupo Sanguíneo',
    hospitalBranch: 'Sede del Hospital',
    liveQueueTitle: 'Seguimiento de Fila en Vivo',
    selectDept: 'Seleccionar Departamento',
    currentToken: 'Turno Actual',
    nowConsulting: 'CONSULTANDO AHORA',
    waitMessage: 'Por favor espere, su turno se acerca.',
    queueProgress: 'Progreso de la Fila',
    tokenGenerated: 'Turno Generado',
    almostYourTurn: 'Casi es su turno',
    yourTurn: 'Su Turno',
    refreshStatus: 'Actualizar Estado',
    autoRefreshOn: 'Actualización en vivo activada',
    patientsWaiting: 'Pacientes en Espera',
    bookDoctorVisit: 'Reservar Cita Médica',
    step: 'Paso',
    selectDoctor: 'Seleccionar Médico',
    selectDate: 'Seleccionar Fecha',
    selectTime: 'Seleccionar Horario',
    confirmBooking: 'Confirmar Cita',
    continueBtn: 'Continuar',
    backBtn: 'Atrás',
    bookingSuccess: '¡Cita Confirmada!',
    tokenGeneratedNotice: 'Su turno digital ha sido generado con éxito',
    close: 'Cerrar',
    settingsTitle: 'Ajustes y Preferencias',
    settingsSubtitle: 'Idioma, alertas de voz y opciones de accesibilidad',
    selectLang: 'Seleccionar Idioma de la Aplicación',
    chooseLangDesc: 'Elija su idioma preferido para el seguimiento de turnos y alertas del hospital:',
    queueAlerts: 'Configuración de Audio y Alertas',
    voiceAnnounce: 'Anuncios de Voz de Fila',
    voiceDesc: 'Campana sonora cuando avanza el número de turno',
    smsAlerts: 'Actualizaciones por SMS / WhatsApp',
    smsDesc: 'Reciba recordatorio cuando queden 2 pacientes por delante',
    seniorMode: 'Modo Alto Contraste / Adultos Mayores',
    seniorDesc: 'Pantalla de turnos ampliada para visibilidad en pasillos',
    emergencyContact: 'Línea de Emergencia Hospitalaria',
    emergency247: 'Disponible 24/7 para atención médica urgente',
    dialHelp: 'Llamar 108 / 911',
    smartQueueSys: 'Sistema Inteligente de Gestión de Filas Hospitalarias',
    selectLoginRole: 'Seleccionar Rol de Ingreso:',
    loginAs: 'Ingresar como',
    signUp: 'Registrarse',
    skipForNow: 'Omitir por ahora',
    useDemoCredentials: 'Usar credenciales Demo con 1 clic',
    orTypeCustom: 'O escribir correo y contraseña',
    onDuty: 'De Guardia',
    todayQueue: 'Fila de Hoy',
    completedConsultations: 'Consultas Completadas',
    currentPatient: 'Paciente Actual en Consulta',
    callNext: 'Llamar al Siguiente',
    completeConsultation: 'Completar Consulta',
    hospitalOverview: 'Operaciones del Hospital',
    todayAppointments: 'Citas de Hoy',
    avgWait: 'Tiempo de Espera Promedio',
    liveHospitalQueue: 'Fila del Hospital en Vivo',
  },
  fr: {
    appName: 'QuickCare',
    appSubtitle: "Système Intelligent de Gestion des Files d'Attente Hospitalières",
    liveMode: 'Mode en Direct QuickCare',
    bookAppointment: 'Prendre Rendez-vous',
    notifications: 'Notifications',
    signOut: 'Déconnexion',
    patient: 'Patient',
    doctor: 'Médecin',
    admin: 'Administrateur',
    patientRavi: 'Patient (Ravi)',
    doctorRamesh: 'Médecin (Dr. Ramesh)',
    hospitalAdmin: "Admin de l'Hôpital",
    switchActiveRole: 'Changer de Rôle',
    navHome: 'Accueil',
    navAppointments: 'Rendez-vous',
    navTracker: "File d'Attente",
    navProfile: 'Profil',
    patientPortal: 'Portail Patient',
    greeting: 'Bonjour',
    queueSummary: "Résumé de votre File d'Attente",
    hospitalStatus: "Statut d'admission hospitalière en direct",
    refresh: 'Actualiser',
    bookNew: 'Nouveau Rendez-vous',
    activeTicket: "TICKET DE FILE D'ATTENTE ACTIF",
    yourToken: 'Votre Numéro',
    inQueue: "Dans la File d'Attente",
    nextInLine: 'Prochain en Ligne',
    consultationActive: 'Consultation en Cours',
    doctorLabel: 'Médecin',
    appointmentDate: 'Date du Rendez-vous',
    estimatedWait: 'Temps d’Attente Estimé',
    peopleAhead: 'Personnes Devant',
    openLiveTracker: 'Ouvrir le Suivi en Direct',
    liveQueueStatus: "Statut de la File d'Attente en Direct",
    token: 'Numéro',
    patientName: 'Nom du Patient',
    department: 'Département',
    waitTime: "Temps d'Attente",
    status: 'Statut',
    completed: 'Terminé',
    current: 'En Cours',
    upcoming: 'À Venir',
    mins: 'min',
    today: "Aujourd'hui",
    pastRecords: 'Historique des Consultations',
    verifiedId: 'Identifiant Patient QuickCare Vérifié',
    contactPhone: 'Téléphone de Contact',
    ageGender: 'Âge & Sexe',
    bloodGroup: 'Groupe Sanguin',
    hospitalBranch: "Branche de l'Hôpital",
    liveQueueTitle: "Suivi de File d'Attente en Direct",
    selectDept: 'Sélectionner le Département',
    currentToken: 'Numéro Actuel',
    nowConsulting: 'EN CONSULTATION',
    waitMessage: 'Veuillez patienter, votre tour approche.',
    queueProgress: "Progression de la File d'Attente",
    tokenGenerated: 'Numéro Généré',
    almostYourTurn: 'Bientôt votre tour',
    yourTurn: 'À Votre Tour',
    refreshStatus: 'Actualiser le Statut',
    autoRefreshOn: 'Actualisation automatique active',
    patientsWaiting: 'Patients en Attente',
    bookDoctorVisit: 'Prendre un Rendez-vous Médical',
    step: 'Étape',
    selectDoctor: 'Choisir un Médecin',
    selectDate: 'Choisir la Date',
    selectTime: "Choisir l'Heure",
    confirmBooking: 'Confirmer le Rendez-vous',
    continueBtn: 'Continuer',
    backBtn: 'Retour',
    bookingSuccess: 'Rendez-vous Confirmé !',
    tokenGeneratedNotice: 'Votre numéro de file numérique a été créé avec succès',
    close: 'Fermer',
    settingsTitle: 'Paramètres & Préférences',
    settingsSubtitle: "Langue, alertes vocales & options d'accessibilité",
    selectLang: "Sélectionner la Langue de l'Application",
    chooseLangDesc: "Choisissez votre langue préférée pour le suivi de la file et les annonces de l'hôpital :",
    queueAlerts: 'Paramètres Audio & Alertes',
    voiceAnnounce: 'Annonces Vocales de File',
    voiceDesc: 'Carillon sonore lorsque le numéro avance',
    smsAlerts: 'Mises à jour SMS / WhatsApp',
    smsDesc: 'Recevez un rappel lorsqu’il ne reste que 2 patients devant vous',
    seniorMode: 'Mode Haut Contraste / Séniors',
    seniorDesc: 'Affichage agrandi du numéro pour les couloirs hospitaliers',
    emergencyContact: "Urgences de l'Hôpital",
    emergency247: 'Disponible 24h/24 et 7j/7 pour soins urgents',
    dialHelp: 'Composer le 108 / 911',
    smartQueueSys: "Système Intelligent de Gestion des Files d'Attente Hospitalières",
    selectLoginRole: 'Sélectionner le Rôle de Connexion :',
    loginAs: 'Se connecter en tant que',
    signUp: "S'inscrire",
    skipForNow: 'Ignorer pour le moment',
    useDemoCredentials: 'Identifiants Démo en 1 clic',
    orTypeCustom: 'Ou saisir email & mot de passe',
    onDuty: 'En Service',
    todayQueue: "File d'Attente du Jour",
    completedConsultations: 'Consultations Terminées',
    currentPatient: 'Patient Actuel en Consultation',
    callNext: 'Appeler le Suivant',
    completeConsultation: 'Terminer la Consultation',
    hospitalOverview: 'Opérations Hospitalières',
    todayAppointments: "Rendez-vous d'Aujourd'hui",
    avgWait: "Temps d'Attente Moyen",
    liveHospitalQueue: "File d'Attente en Direct",
  },
  ar: {
    appName: 'كويك كير',
    appSubtitle: 'نظام إدارة طوابير المستشفيات الذكي',
    liveMode: 'وضع كويك كير المباشر',
    bookAppointment: 'حجز موعد',
    notifications: 'الإشعارات',
    signOut: 'تسجيل الخروج',
    patient: 'المريض',
    doctor: 'الطبيب',
    admin: 'مدير المستشفى',
    patientRavi: 'المريض (رافي)',
    doctorRamesh: 'الطبيب (د. راميش)',
    hospitalAdmin: 'إدارة المستشفى',
    switchActiveRole: 'تبديل الدور الحالي',
    navHome: 'الرئيسية',
    navAppointments: 'المواعيد',
    navTracker: 'متابع الطابور',
    navProfile: 'الملف الشخصي',
    patientPortal: 'بوابة المريض',
    greeting: 'مرحبا',
    queueSummary: 'ملخص دورك في الطابور',
    hospitalStatus: 'حالة الطابور المباشرة في المستشفى',
    refresh: 'تحديث',
    bookNew: 'حجز موعد جديد',
    activeTicket: 'تذكرة الطابور النشطة',
    yourToken: 'رقم دورك',
    inQueue: 'في الانتظار',
    nextInLine: 'التالي في الطابور',
    consultationActive: 'الكشف جارٍ الآن',
    doctorLabel: 'الطبيب',
    appointmentDate: 'تاريخ الموعد',
    estimatedWait: 'الوقت المقدر للانتظار',
    peopleAhead: 'الأشخاص قبلك',
    openLiveTracker: 'فتح التتبع المباشر للطابور',
    liveQueueStatus: 'حالة الطابور المباشرة',
    token: 'الرقم',
    patientName: 'اسم المريض',
    department: 'القسم',
    waitTime: 'وقت الانتظار',
    status: 'الحالة',
    completed: 'مكتمل',
    current: 'حالي',
    upcoming: 'قادم',
    mins: 'دقيقة',
    today: 'اليوم',
    pastRecords: 'سجل الكشوفات السابقة',
    verifiedId: 'رقم هوية المريض المعتمد',
    contactPhone: 'رقم الهاتف',
    ageGender: 'العمر والجنس',
    bloodGroup: 'فصيلة الدم',
    hospitalBranch: 'فرع المستشفى',
    liveQueueTitle: 'تتبع الطابور المباشر',
    selectDept: 'اختر القسم',
    currentToken: 'الرقم الحالي',
    nowConsulting: 'يتم الكشف الآن',
    waitMessage: 'يرجى الانتظار، دورك قادم قريباً.',
    queueProgress: 'تقدم الطابور',
    tokenGenerated: 'تم إصدار التذكرة',
    almostYourTurn: 'اقترب دورك جداً',
    yourTurn: 'حان دورك الآن',
    refreshStatus: 'تحديث الحالة',
    autoRefreshOn: 'التحديث التلقائي قيد التشغيل',
    patientsWaiting: 'مرضى في الانتظار',
    bookDoctorVisit: 'حجز موعد مع الطبيب',
    step: 'الخطوة',
    selectDoctor: 'اختر الطبيب',
    selectDate: 'اختر التاريخ',
    selectTime: 'اختر الوقت',
    confirmBooking: 'تأكيد الموعد',
    continueBtn: 'متابعة',
    backBtn: 'رجوع',
    bookingSuccess: 'تم تأكيد الموعد بنجاح!',
    tokenGeneratedNotice: 'تم إنشاء تذكرتك الرقمية بنجاح',
    close: 'إغلاق',
    settingsTitle: 'الإعدادات والتفضيلات',
    settingsSubtitle: 'خيارات اللغة والصوت وإمكانية الوصول',
    selectLang: 'اختر لغة التطبيق',
    chooseLangDesc: 'اختر لغتك المفضلة لمتابعة الطابور وإشعارات المستشفى:',
    queueAlerts: 'إعدادات تنبيهات وصوت الطابور',
    voiceAnnounce: 'إعلانات الطابور الصوتية',
    voiceDesc: 'رنين صوتي عند تقدم رقم التذكرة',
    smsAlerts: 'تنبيهات الرسائل القصيرة والواتساب',
    smsDesc: 'استلام تذكير عند بقاء شخصين فقط قبلك',
    seniorMode: 'التباين العالي / وضع كبار السن',
    seniorDesc: 'عرض أرقام كبير لتسهيل الرؤية في الممرات',
    emergencyContact: 'مكتب طوارئ المستشفى',
    emergency247: 'متاح على مدار الساعة للحالات الحرجة',
    dialHelp: 'اتصل على 108 / 911',
    smartQueueSys: 'نظام إدارة طوابير المستشفيات الذكي',
    selectLoginRole: 'اختر دور تسجيل الدخول:',
    loginAs: 'تسجيل الدخول كـ',
    signUp: 'إنشاء حساب',
    skipForNow: 'تخطي الآن',
    useDemoCredentials: 'استخدام بيانات الدخول التجريبية',
    orTypeCustom: 'أو كتابة البريد وكلمة المرور',
    onDuty: 'في الخدمة',
    todayQueue: 'طابور اليوم',
    completedConsultations: 'الكشوفات المكتملة',
    currentPatient: 'المريض الحالي في الكشف',
    callNext: 'مناداة المريض التالي',
    completeConsultation: 'إنهاء الكشف',
    hospitalOverview: 'نظرة عامة على عمليات المستشفى',
    todayAppointments: 'مواعيد اليوم',
    avgWait: 'متوسط وقت الانتظار',
    liveHospitalQueue: 'طابور المستشفى المباشر',
  },
  de: {
    appName: 'QuickCare',
    appSubtitle: 'Intelligentes Krankenhaus-Warteschlangen-Managementsystem',
    liveMode: 'QuickCare Live-Modus',
    bookAppointment: 'Termin buchen',
    notifications: 'Benachrichtigungen',
    signOut: 'Abmelden',
    patient: 'Patient',
    doctor: 'Arzt',
    admin: 'Administrator',
    patientRavi: 'Patient (Ravi)',
    doctorRamesh: 'Arzt (Dr. Ramesh)',
    hospitalAdmin: 'Krankenhaus-Admin',
    switchActiveRole: 'Rolle wechseln',
    navHome: 'Start',
    navAppointments: 'Termine',
    navTracker: 'Warteschlange',
    navProfile: 'Profil',
    patientPortal: 'Patientenportal',
    greeting: 'Hallo',
    queueSummary: 'Ihre Warteschlangen-Übersicht',
    hospitalStatus: 'Live-Status der Krankenhausaufnahme',
    refresh: 'Aktualisieren',
    bookNew: 'Neu buchen',
    activeTicket: 'AKTIVES WARTETICKET',
    yourToken: 'Ihre Nummer',
    inQueue: 'In der Warteschlange',
    nextInLine: 'Als Nächstes an der Reihe',
    consultationActive: 'Behandlung läuft',
    doctorLabel: 'Arzt',
    appointmentDate: 'Termindatum',
    estimatedWait: 'Geschätzte Wartezeit',
    peopleAhead: 'Personen vor Ihnen',
    openLiveTracker: 'Live-Tracker öffnen',
    liveQueueStatus: 'Live-Warteschlangen-Status',
    token: 'Nummer',
    patientName: 'Patientenname',
    department: 'Abteilung',
    waitTime: 'Wartezeit',
    status: 'Status',
    completed: 'Abgeschlossen',
    current: 'Aktuell',
    upcoming: 'Bevorstehend',
    mins: 'Min.',
    today: 'Heute',
    pastRecords: 'Frühere Behandlungen',
    verifiedId: 'Verifizierte QuickCare Patienten-ID',
    contactPhone: 'Telefonnummer',
    ageGender: 'Alter & Geschlecht',
    bloodGroup: 'Blutgruppe',
    hospitalBranch: 'Krankenhaus-Standort',
    liveQueueTitle: 'Live-Warteschlangen-Verfolgung',
    selectDept: 'Abteilung wählen',
    currentToken: 'Aktuelle Nummer',
    nowConsulting: 'JETZT IN BEHANDLUNG',
    waitMessage: 'Bitte warten Sie, Sie sind gleich an der Reihe.',
    queueProgress: 'Warteschlangen-Fortschritt',
    tokenGenerated: 'Nummer erstellt',
    almostYourTurn: 'Gleich an der Reihe',
    yourTurn: 'Sie sind an der Reihe',
    refreshStatus: 'Status aktualisieren',
    autoRefreshOn: 'Automatische Live-Aktualisierung aktiv',
    patientsWaiting: 'Wartende Patienten',
    bookDoctorVisit: 'Arzttermin buchen',
    step: 'Schritt',
    selectDoctor: 'Arzt auswählen',
    selectDate: 'Datum auswählen',
    selectTime: 'Uhrzeit auswählen',
    confirmBooking: 'Termin bestätigen',
    continueBtn: 'Weiter',
    backBtn: 'Zurück',
    bookingSuccess: 'Termin erfolgreich bestätigt!',
    tokenGeneratedNotice: 'Ihre digitale Wartenummer wurde generiert',
    close: 'Schließen',
    settingsTitle: 'Einstellungen & Präferenzen',
    settingsSubtitle: 'Sprache, Audio-Signale & Barrierefreiheit',
    selectLang: 'App-Sprache auswählen',
    chooseLangDesc: 'Wählen Sie Ihre bevorzugte Sprache für Nummernverfolgung und Krankenhausdurchsagen:',
    queueAlerts: 'Audio- & Benachrichtigungseinstellungen',
    voiceAnnounce: 'Sprachansage bei Aufruf',
    voiceDesc: 'Tonsignal bei Vorrücken der Wartenummer',
    smsAlerts: 'SMS- / WhatsApp-Updates',
    smsDesc: 'Erinnerung erhalten, wenn noch 2 Personen vor Ihnen sind',
    seniorMode: 'Hoher Kontrast / Senioren-Modus',
    seniorDesc: 'Vergrößerte Anzeige für gute Lesbarkeit im Flur',
    emergencyContact: 'Krankenhaus Notfall-Hotline',
    emergency247: '24/7 für dringende medizinische Fälle erreichbar',
    dialHelp: 'Wähle 108 / 911',
    smartQueueSys: 'Intelligentes Krankenhaus-Warteschlangen-Managementsystem',
    selectLoginRole: 'Anmelderolle auswählen:',
    loginAs: 'Anmelden als',
    signUp: 'Registrieren',
    skipForNow: 'Jetzt überspringen',
    useDemoCredentials: '1-Klick Demo-Zugangsdaten',
    orTypeCustom: 'Oder E-Mail & Passwort eingeben',
    onDuty: 'Im Dienst',
    todayQueue: 'Heutige Warteschlange',
    completedConsultations: 'Abgeschlossene Behandlungen',
    currentPatient: 'Aktueller Patient',
    callNext: 'Nächsten Patienten aufrufen',
    completeConsultation: 'Behandlung abschließen',
    hospitalOverview: 'Betriebsübersicht',
    todayAppointments: 'Heutige Termine',
    avgWait: 'Durchschnittliche Wartezeit',
    liveHospitalQueue: 'Live-Warteschlange',
  },
  bn: {
    appName: 'কুইককেয়ার',
    appSubtitle: 'স্মার্ট হাসপাতাল সারি পরিচালনা ব্যবস্থা',
    liveMode: 'কুইককেয়ার লাইভ মোড',
    bookAppointment: 'অ্যাপয়েন্টমেন্ট বুক করুন',
    notifications: 'বিজ্ঞপ্তি',
    signOut: 'সাইন আউট',
    patient: 'রোগী',
    doctor: 'ডাক্তার',
    admin: 'প্রশাসক',
    patientRavi: 'রোগী (রবি)',
    doctorRamesh: 'ডাক্তার (ডাঃ রমেশ)',
    hospitalAdmin: 'হাসপাতাল অ্যাডমিন',
    switchActiveRole: 'সক্রিয় ভূমিকা পরিবর্তন করুন',
    navHome: 'হোম',
    navAppointments: 'অ্যাপয়েন্টমেন্ট',
    navTracker: 'সারি ট্র্যাকার',
    navProfile: 'প্রোফাইল',
    patientPortal: 'রোগী পোর্টাল',
    greeting: 'নমস্কার',
    queueSummary: 'আপনার সারির সংক্ষিপ্ত বিবরণ',
    hospitalStatus: 'লাইভ হাসপাতালের ভর্তি অবস্থা',
    refresh: 'রিফ্রেশ করুন',
    bookNew: 'নতুন বুক করুন',
    activeTicket: 'সক্রিয় সারি টোকেন',
    yourToken: 'আপনার টোকেন',
    inQueue: 'সারিতে আছে',
    nextInLine: 'সারিতে পরবর্তী',
    consultationActive: 'পরামর্শ চলছে',
    doctorLabel: 'ডাক্তার',
    appointmentDate: 'অ্যাপয়েন্টমেন্টের তারিখ',
    estimatedWait: 'আনুমানিক অপেক্ষার সময়',
    peopleAhead: 'সামনে অপেক্ষারত রোগী',
    openLiveTracker: 'লাইভ ট্র্যাকার খুলুন',
    liveQueueStatus: 'লাইভ সারির অবস্থা',
    token: 'টোকেন',
    patientName: 'রোগীর নাম',
    department: 'বিভাগ',
    waitTime: 'অপেক্ষার সময়',
    status: 'অবস্থা',
    completed: 'সম্পন্ন',
    current: 'বর্তমান',
    upcoming: 'আসন্ন',
    mins: 'মিনিট',
    today: 'আজ',
    pastRecords: 'পূর্ববর্তী পরামর্শ রেকর্ড',
    verifiedId: 'যাচাইকৃত রোগী আইডি',
    contactPhone: 'যোগাযোগের ফোন',
    ageGender: 'বয়স ও লিঙ্গ',
    bloodGroup: 'রক্তের গ্রুপ',
    hospitalBranch: 'হাসপাতালের শাখা',
    liveQueueTitle: 'লাইভ সারি ট্র্যাকিং',
    selectDept: 'বিভাগ নির্বাচন করুন',
    currentToken: 'বর্তমান টোকেন',
    nowConsulting: 'এখন পরামর্শ চলছে',
    waitMessage: 'দয়া করে অপেক্ষা করুন, শীঘ্রই আপনার পালা আসছে।',
    queueProgress: 'সারির অগ্রগতি',
    tokenGenerated: 'টোকেন তৈরি হয়েছে',
    almostYourTurn: 'প্রায় আপনার পালা',
    yourTurn: 'আপনার পালা এসেছে',
    refreshStatus: 'অবস্থা রিফ্রেশ করুন',
    autoRefreshOn: 'স্বয়ংক্রিয় রিফ্রেশ সক্রিয়',
    patientsWaiting: 'অপেক্ষারত রোগী',
    bookDoctorVisit: 'ডাক্তারের অ্যাপয়েন্টমেন্ট বুক করুন',
    step: 'ধাপ',
    selectDoctor: 'ডাক্তার নির্বাচন করুন',
    selectDate: 'তারিখ নির্বাচন করুন',
    selectTime: 'সময় নির্বাচন করুন',
    confirmBooking: 'অ্যাপয়েন্টমেন্ট নিশ্চিত করুন',
    continueBtn: 'এগিয়ে যান',
    backBtn: 'পেছনে যান',
    bookingSuccess: 'অ্যাপয়েন্টমেন্ট নিশ্চিত হয়েছে!',
    tokenGeneratedNotice: 'আপনার ডিজিটাল টোকেন সফলভাবে তৈরি হয়েছে',
    close: 'বন্ধ করুন',
    settingsTitle: 'সেটিংস ও পছন্দসমূহ',
    settingsSubtitle: 'ভাষা, ভয়েস ও অন্যান্য বিকল্প',
    selectLang: 'অ্যাপের ভাষা নির্বাচন করুন',
    chooseLangDesc: 'টোকেন ট্র্যাকিং ও হাসপাতাল সারির জন্য আপনার পছন্দের ভাষা নির্বাচন করুন:',
    queueAlerts: 'সারি অডিও ও সতর্কবার্তা সেটিংস',
    voiceAnnounce: 'সারি ভয়েস ঘোষণা',
    voiceDesc: 'টোকেন নম্বর এগিয়ে গেলে অডিও বেল',
    smsAlerts: 'এসএমএস / হোয়াটসঅ্যাপ আপডেট',
    smsDesc: 'সামনে ২ জন থাকলে সতর্কতা পান',
    seniorMode: 'হাই কনট্রাস্ট / সিনিয়র মোড',
    seniorDesc: 'সহজে দেখার জন্য বড় টোকেন ডিসপ্লে',
    emergencyContact: 'হাসপাতাল জরুরি হেল্পডেস্ক',
    emergency247: 'জরুরি চিকিৎসার জন্য ২৪/৭ উপলব্ধ',
    dialHelp: 'ডায়াল করুন ১০৮ / ৯১১',
    smartQueueSys: 'স্মার্ট হাসপাতাল সারি পরিচালনা ব্যবস্থা',
    selectLoginRole: 'লগইন ভূমিকা নির্বাচন করুন:',
    loginAs: 'হিসাবে লগইন করুন',
    signUp: 'নিবন্ধন করুন',
    skipForNow: 'এখনই এড়িয়ে যান',
    useDemoCredentials: '১-ক্লিক ডেমো ব্যবহার করুন',
    orTypeCustom: 'অথবা ইমেল ও পাসওয়ার্ড দিন',
    onDuty: 'দায়িত্বরত',
    todayQueue: 'আজকের সারি',
    completedConsultations: 'সম্পন্ন পরামর্শ',
    currentPatient: 'বর্তমান পরামর্শরত রোগী',
    callNext: 'পরবর্তী রোগীকে ডাকুন',
    completeConsultation: 'পরামর্শ সম্পন্ন করুন',
    hospitalOverview: 'হাসপাতাল পরিচালনা চিত্র',
    todayAppointments: 'আজকের অ্যাপয়েন্টমেন্ট',
    avgWait: 'গড় অপেক্ষার সময়',
    liveHospitalQueue: 'লাইভ হাসপাতাল সারি',
  },
  mr: {
    appName: 'क्विककेअर',
    appSubtitle: 'स्मार्ट रुग्णालय रांग व्यवस्थापन प्रणाली',
    liveMode: 'क्विककेअर थेट मोड',
    bookAppointment: 'अपॉइंटमेंट बुक करा',
    notifications: 'सूचना',
    signOut: 'बाहेर पडा',
    patient: 'रुग्ण',
    doctor: 'डॉक्टर',
    admin: 'प्रशासक',
    patientRavi: 'रुग्ण (रवी)',
    doctorRamesh: 'डॉक्टर (डॉ. रमेश)',
    hospitalAdmin: 'हॉस्पिटल ॲडमिन',
    switchActiveRole: 'सक्रिय भूमिका बदला',
    navHome: 'मुख्यपृष्ठ',
    navAppointments: 'अपॉइंटमेंट्स',
    navTracker: 'रांग ट्रॅकर',
    navProfile: 'प्रोफाइल',
    patientPortal: 'रुग्ण पोर्टल',
    greeting: 'नमस्कार',
    queueSummary: 'तुमचा रांग सारांश',
    hospitalStatus: 'थेट रुग्णालय रांग स्थिती',
    refresh: 'रिफ्रेश करा',
    bookNew: 'नवीन बुक करा',
    activeTicket: 'सक्रिय रांग टोकन',
    yourToken: 'तुमचा टोकन',
    inQueue: 'रांगेत आहे',
    nextInLine: 'रांगेत पुढील',
    consultationActive: 'सल्लामसलत सुरू आहे',
    doctorLabel: 'डॉक्टर',
    appointmentDate: 'अपॉइंटमेंट तारीख',
    estimatedWait: 'अंदाजे प्रतीक्षा वेळ',
    peopleAhead: 'तुमच्या पुढे लोक',
    openLiveTracker: 'थेट ट्रॅकर उघडा',
    liveQueueStatus: 'थेट रांग स्थिती',
    token: 'टोकन',
    patientName: 'रुग्णाचे नाव',
    department: 'विभाग',
    waitTime: 'प्रतीक्षा वेळ',
    status: 'स्थिती',
    completed: 'पूर्ण झाले',
    current: 'सध्याचे',
    upcoming: 'आगामी',
    mins: 'मिनिटे',
    today: 'आज',
    pastRecords: 'मागील तपासणी नोंदी',
    verifiedId: 'सत्यापित रुग्ण आयडी',
    contactPhone: 'फोन नंबर',
    ageGender: 'वय आणि लिंग',
    bloodGroup: 'रक्तगट',
    hospitalBranch: 'रुग्णालय शाखा',
    liveQueueTitle: 'थेट रांग ट्रॅकिंग',
    selectDept: 'विभाग निवडा',
    currentToken: 'सध्याचा टोकन',
    nowConsulting: 'सध्या तपासणी सुरू आहे',
    waitMessage: 'कृपया प्रतीक्षा करा, तुमचा नंबर लवकरच येत आहे.',
    queueProgress: 'रांगेची प्रगती',
    tokenGenerated: 'टोकन तयार झाला',
    almostYourTurn: 'लवकरच तुमची पाळी',
    yourTurn: 'तुमची पाळी आली',
    refreshStatus: 'स्थिती रिफ्रेश करा',
    autoRefreshOn: 'ऑटो-रिफ्रेश चालू आहे',
    patientsWaiting: 'प्रतीक्षारत रुग्ण',
    bookDoctorVisit: 'डॉक्टर अपॉइंटमेंट बुक करा',
    step: 'टप्पा',
    selectDoctor: 'डॉक्टर निवडा',
    selectDate: 'तारीख निवडा',
    selectTime: 'वेळ निवडा',
    confirmBooking: 'अपॉइंटमेंट निश्चित करा',
    continueBtn: 'पुढे जा',
    backBtn: 'मागे जा',
    bookingSuccess: 'अपॉइंटमेंट निश्चित झाली!',
    tokenGeneratedNotice: 'तुमचा डिजिटल टोकन तयार झाला आहे',
    close: 'बंद करा',
    settingsTitle: 'सेटिंग्ज आणि प्राधान्ये',
    settingsSubtitle: 'भाषा, आवाज आणि प्रवेशयोग्यता पर्याय',
    selectLang: 'ॲप्लिकेशनची भाषा निवडा',
    chooseLangDesc: 'टोकन ट्रॅकिंग आणि रुग्णालय रांगेसाठी तुमची भाषा निवडा:',
    queueAlerts: 'रांग ऑडिओ आणि सूचना सेटिंग्ज',
    voiceAnnounce: 'रांग आवाज घोषणा',
    voiceDesc: 'टोकन पुढे सरकल्यावर आवाज',
    smsAlerts: 'एसएमएस / व्हॉट्सॲप अपडेट्स',
    smsDesc: 'पुढे २ रुग्ण शिल्लक असताना सूचना मिळवा',
    seniorMode: 'हाय कॉन्ट्रास्ट / ज्येष्ठ मोड',
    seniorDesc: 'सहज दिसण्यासाठी मोठा टोकन डिस्प्ले',
    emergencyContact: 'रुग्णालय आणीबाणी हेल्पडेस्क',
    emergency247: 'तात्काळ उपचारांसाठी २४/७ उपलब्ध',
    dialHelp: 'डायल १०८ / ९११',
    smartQueueSys: 'स्मार्ट रुग्णालय रांग व्यवस्थापन प्रणाली',
    selectLoginRole: 'लॉगिन भूमिका निवडा:',
    loginAs: 'म्हणून लॉगिन करा',
    signUp: 'साइन अप करा',
    skipForNow: 'आत्ता वगळा',
    useDemoCredentials: '१-क्लिक डेमो वापरा',
    orTypeCustom: 'किंवा ईमेल आणि पासवर्ड प्रविष्ट करा',
    onDuty: 'कर्तव्यावर',
    todayQueue: 'आजची रांग',
    completedConsultations: 'पूर्ण झालेल्या तपासण्या',
    currentPatient: 'सध्याचा रुग्ण',
    callNext: 'पुढील रुग्णाला बोलवा',
    completeConsultation: 'तपासणी पूर्ण करा',
    hospitalOverview: 'रुग्णालय कामकाज आढावा',
    todayAppointments: 'आजच्या अपॉइंटमेंट्स',
    avgWait: 'सरासरी प्रतीक्षा वेळ',
    liveHospitalQueue: 'थेट रुग्णालय रांग',
  },
  kn: {
    appName: 'ಕ್ವಿಕ್‌ಕೇರ್',
    appSubtitle: 'ಸ್ಮಾರ್ಟ್ ಆಸ್ಪತ್ರೆ ಕ್ಯೂ ನಿರ್ವಹಣಾ ವ್ಯವಸ್ಥೆ',
    liveMode: 'ಕ್ವಿಕ್‌ಕೇರ್ ಲೈವ್ ಮೋಡ್',
    bookAppointment: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಿ',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    signOut: 'ಸೈನ್ ಔಟ್',
    patient: 'ರೋಗಿ',
    doctor: 'ವೈದ್ಯರು',
    admin: 'ಆಡಳಿತಾಧಿಕಾರಿ',
    patientRavi: 'ರೋಗಿ (ರವಿ)',
    doctorRamesh: 'ವೈದ್ಯರು (ಡಾ. ರಮೇಶ್)',
    hospitalAdmin: 'ಆಸ್ಪತ್ರೆ ನಿರ್ವಾಹಕರು',
    switchActiveRole: 'ಪಾತ್ರವನ್ನು ಬದಲಾಯಿಸಿ',
    navHome: 'ಮುಖಪುಟ',
    navAppointments: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು',
    navTracker: 'ಕ್ಯೂ ಟ್ರ್ಯಾಕರ್',
    navProfile: 'ಪ್ರೊಫೈಲ್',
    patientPortal: 'ರೋಗಿ ಪೋರ್ಟಲ್',
    greeting: 'ನಮಸ್ಕಾರ',
    queueSummary: 'ನಿಮ್ಮ ಕ್ಯೂ ವಿವರ',
    hospitalStatus: 'ಲೈವ್ ಆಸ್ಪತ್ರೆ ಪ್ರವೇಶ ಸ್ಥಿತಿ',
    refresh: 'ರಿಫ್ರೆಶ್ ಮಾಡಿ',
    bookNew: 'ಹೊಸದನ್ನು ಬುಕ್ ಮಾಡಿ',
    activeTicket: 'ಸಕ್ರಿಯ ಕ್ಯೂ ಟೋಕನ್',
    yourToken: 'ನಿಮ್ಮ ಟೋಕನ್',
    inQueue: 'ಕ್ಯೂನಲ್ಲಿದೆ',
    nextInLine: 'ಮುಂದಿನ ಸರದಿ',
    consultationActive: 'ಸಮಾಲೋಚನೆ ನಡೆಯುತ್ತಿದೆ',
    doctorLabel: 'ವೈದ್ಯರು',
    appointmentDate: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ದಿನಾಂಕ',
    estimatedWait: 'ಅಂದಾಜು ಕಾಯುವ ಸಮಯ',
    peopleAhead: 'ಮುಂದಿರುವವರು',
    openLiveTracker: 'ಲೈವ್ ಟ್ರ್ಯಾಕರ್ ತೆರೆಯಿರಿ',
    liveQueueStatus: 'ಲೈವ್ ಕ್ಯೂ ಸ್ಥಿತಿ',
    token: 'ಟೋಕನ್',
    patientName: 'ರೋಗಿಯ ಹೆಸರು',
    department: 'ವಿಭಾಗ',
    waitTime: 'ಕಾಯುವ ಸಮಯ',
    status: 'ಸ್ಥಿತಿ',
    completed: 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    current: 'ಪ್ರಸ್ತುತ',
    upcoming: 'ಮುಂಬರುವ',
    mins: 'ನಿಮಿಷಗಳು',
    today: 'ಇಂದು',
    pastRecords: 'ಹಿಂದಿನ ತಪಾಸಣೆ ದಾಖಲೆಗಳು',
    verifiedId: 'ಪರಿಶೀಲಿಸಿದ ರೋಗಿ ಐಡಿ',
    contactPhone: 'ಸಂಪರ್ಕ ಫೋನ್',
    ageGender: 'ವಯಸ್ಸು ಮತ್ತು ಲಿಂಗ',
    bloodGroup: 'ರಕ್ತದ ಗುಂಪು',
    hospitalBranch: 'ಆಸ್ಪತ್ರೆ ಶಾಖೆ',
    liveQueueTitle: 'ಲೈವ್ ಕ್ಯೂ ಟ್ರ್ಯಾಕಿಂಗ್',
    selectDept: 'ವಿಭಾಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    currentToken: 'ಪ್ರಸ್ತುತ ಟೋಕನ್',
    nowConsulting: 'ಈಗ ತಪಾಸಣೆ ನಡೆಯುತ್ತಿದೆ',
    waitMessage: 'ದಯವಿಟ್ಟು ಕಾಯಿರಿ, ನಿಮ್ಮ ಸರದಿ ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ.',
    queueProgress: 'ಕ್ಯೂ ಪ್ರಗತಿ',
    tokenGenerated: 'ಟೋಕನ್ ರಚಿಸಲಾಗಿದೆ',
    almostYourTurn: 'ನಿಮ್ಮ ಸರದಿ ಹತ್ತಿರದಲ್ಲಿದೆ',
    yourTurn: 'ನಿಮ್ಮ ಸರದಿ ಬಂದಿದೆ',
    refreshStatus: 'ಸ್ಥಿತಿ ರಿಫ್ರೆಶ್ ಮಾಡಿ',
    autoRefreshOn: 'ಲೈವ್ ಆಟೋ-ರಿಫ್ರೆಶ್ ಸಕ್ರಿಯವಾಗಿದೆ',
    patientsWaiting: 'ಕಾಯುತ್ತಿರುವ ರೋಗಿಗಳು',
    bookDoctorVisit: 'ವೈದ್ಯರ ಭೇಟಿಯನ್ನು ಕಾಯ್ದಿರಿಸಿ',
    step: 'ಹಂತ',
    selectDoctor: 'ವೈದ್ಯರನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    selectDate: 'ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ',
    selectTime: 'ಸಮಯ ಆಯ್ಕೆಮಾಡಿ',
    confirmBooking: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ದೃಢೀಕರಿಸಿ',
    continueBtn: 'ಮುಂದುವರಿಯಿರಿ',
    backBtn: 'ಹಿಂದೆ',
    bookingSuccess: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ದೃಢಪಟ್ಟಿದೆ!',
    tokenGeneratedNotice: 'ನಿಮ್ಮ ಡಿಜಿಟಲ್ ಟೋಕನ್ ರಚಿಸಲಾಗಿದೆ',
    close: 'ಮುಚ್ಚಿ',
    settingsTitle: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು ಮತ್ತು ಆದ್ಯತೆಗಳು',
    settingsSubtitle: 'ಭಾಷೆ, ಧ್ವನಿ ಮತ್ತು ಇತರ ಆಯ್ಕೆಗಳು',
    selectLang: 'ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    chooseLangDesc: 'ಟೋಕನ್ ಟ್ರ್ಯಾಕಿಂಗ್ ಮತ್ತು ಆಸ್ಪತ್ರೆ ಮಾಹಿತಿಗಾಗಿ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ:',
    queueAlerts: 'ಆಡಿಯೋ ಮತ್ತು ಎಚ್ಚರಿಕೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    voiceAnnounce: 'ಧ್ವನಿ ಪ್ರಕಟಣೆಗಳು',
    voiceDesc: 'ಟೋಕನ್ ಮುನ್ನಡೆದಾಗ ಸದ್ದು ಬರುತ್ತದೆ',
    smsAlerts: 'ಎಸ್ಎಂಎಸ್ / ವಾಟ್ಸಾಪ್ ಅಪ್‌ಡೇಟ್‌ಗಳು',
    smsDesc: 'ನಿಮ್ಮ ಮುಂದೆ 2 ರೋಗಿಗಳಿರುವಾಗ ಸಂದೇಶ ಪಡೆಯಿರಿ',
    seniorMode: 'ಹೈ ಕಾಂಟ್ರಾಸ್ಟ್ ಮೋಡ್',
    seniorDesc: 'ದೊಡ್ಡ ಟೋಕನ್ ಡಿಸ್ಪ್ಲೇ',
    emergencyContact: 'ಆಸ್ಪತ್ರೆ ತುರ್ತು ಸಹಾಯವಾಣಿ',
    emergency247: 'ತುರ್ತು ಚಿಕಿತ್ಸೆಗಾಗಿ 24/7 ಲಭ್ಯವಿದೆ',
    dialHelp: 'ಡಯಲ್ ಮಾಡಿ 108 / 911',
    smartQueueSys: 'ಸ್ಮಾರ್ಟ್ ಆಸ್ಪತ್ರೆ ಕ್ಯೂ ನಿರ್ವಹಣಾ ವ್ಯವಸ್ಥೆ',
    selectLoginRole: 'ಲಾಗಿನ್ ಪಾತ್ರ ಆಯ್ಕೆಮಾಡಿ:',
    loginAs: 'ಆಗಿ ಲಾಗಿನ್ ಮಾಡಿ',
    signUp: 'ಸೈನ್ ಅಪ್ ಮಾಡಿ',
    skipForNow: 'ಈಗ ಬಿಟ್ಟುಬಿಡಿ',
    useDemoCredentials: 'ಡೆಮೊ ವಿವರಗಳನ್ನು ಬಳಸಿ',
    orTypeCustom: 'ಅಥವಾ ಇಮೇಲ್ ಮತ್ತು ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ',
    onDuty: 'ಕರ್ತವ್ಯದಲ್ಲಿದ್ದಾರೆ',
    todayQueue: 'ಇಂದಿನ ಕ್ಯೂ',
    completedConsultations: 'ಪೂರ್ಣಗೊಂಡ ತಪಾಸಣೆಗಳು',
    currentPatient: 'ಪ್ರಸ್ತುತ ರೋಗಿ',
    callNext: 'ಮುಂದಿನ ರೋಗಿಯನ್ನು ಕರೆಯಿರಿ',
    completeConsultation: 'ತಪಾಸಣೆ ಪೂರ್ಣಗೊಳಿಸಿ',
    hospitalOverview: 'ಆಸ್ಪತ್ರೆ ಕಾರ್ಯಾಚರಣೆಗಳ ಅವಲೋಕನ',
    todayAppointments: 'ಇಂದಿನ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು',
    avgWait: 'ಸರಾಸರಿ ಕಾಯುವ ಸಮಯ',
    liveHospitalQueue: 'ಲೈವ್ ಆಸ್ಪತ್ರೆ ಕ್ಯೂ',
  },
  ml: {
    appName: 'ക്വിക്ക് കെയർ',
    appSubtitle: 'സ്മാർട്ട് ആശുപത്രി ക്യൂ മാനേജ്മെന്റ് സിസ്റ്റം',
    liveMode: 'ക്വിക്ക് കെയർ ലൈവ് മോഡ്',
    bookAppointment: 'അപ്പോയിന്റ്മെന്റ് ബുക്ക് ചെയ്യുക',
    notifications: 'അറിയിപ്പുകൾ',
    signOut: 'പുറത്തിറങ്ങുക',
    patient: 'രോഗി',
    doctor: 'ഡോക്ടർ',
    admin: 'അഡ്മിനിസ്ട്രേറ്റർ',
    patientRavi: 'രോഗി (രവി)',
    doctorRamesh: 'ഡോക്ടർ (ഡോ. രമേഷ്)',
    hospitalAdmin: 'ആശുപത്രി അഡ്മിൻ',
    switchActiveRole: 'റോൾ മാറ്റുക',
    navHome: 'ഹോം',
    navAppointments: 'അപ്പോയിന്റ്മെന്റുകൾ',
    navTracker: 'ക്യൂ ട്രാക്കർ',
    navProfile: 'പ്രൊഫൈൽ',
    patientPortal: 'രോഗി പോർട്ടൽ',
    greeting: 'നമസ്കാരം',
    queueSummary: 'നിങ്ങളുടെ ക്യൂ വിവരങ്ങൾ',
    hospitalStatus: 'തത്സമയ ആശുപത്രി ക്യൂ നില',
    refresh: 'പുതുക്കുക',
    bookNew: 'പുതിയത് ബുക്ക് ചെയ്യുക',
    activeTicket: 'സജീവ ക്യൂ ടോക്കൺ',
    yourToken: 'നിങ്ങളുടെ ടോക്കൺ',
    inQueue: 'ക്യൂവിലാണ്',
    nextInLine: 'അടുത്ത ഊഴം',
    consultationActive: 'പരിശോധന നടക്കുന്നു',
    doctorLabel: 'ഡോക്ടർ',
    appointmentDate: 'അപ്പോയിന്റ്മെന്റ് തീയതി',
    estimatedWait: 'പ്രതീക്ഷിക്കുന്ന കാത്തിരിപ്പ് സമയം',
    peopleAhead: 'മുന്നിലുള്ള രോഗികൾ',
    openLiveTracker: 'ലൈവ് ട്രാക്കർ തുറക്കുക',
    liveQueueStatus: 'തത്സമയ ക്യൂ നില',
    token: 'ടോക്കൺ',
    patientName: 'രോഗിയുടെ പേര്',
    department: 'വിഭാഗം',
    waitTime: 'കാത്തിരിപ്പ് സമയം',
    status: 'നില',
    completed: 'പൂർത്തിയായി',
    current: 'നിലവിലെ',
    upcoming: 'വരാനിരിക്കുന്ന',
    mins: 'മിനിറ്റ്',
    today: 'ഇന്ന്',
    pastRecords: 'മുമ്പത്തെ പരിശോധനാ രേഖകൾ',
    verifiedId: 'രോഗി ഐഡി',
    contactPhone: 'ഫോൺ നമ്പർ',
    ageGender: 'പ്രായവും ലിംഗവും',
    bloodGroup: 'രക്തഗ്രൂപ്പ്',
    hospitalBranch: 'ആശുപത്രി ശാഖ',
    liveQueueTitle: 'തത്സമയ ക്യൂ ട്രാക്കിംഗ്',
    selectDept: 'വിഭാഗം തിരഞ്ഞെടുക്കുക',
    currentToken: 'നിലവിലെ ടോക്കൺ',
    nowConsulting: 'പരിശോധന നടക്കുന്നു',
    waitMessage: 'ദയവായി കാത്തിരിക്കുക, നിങ്ങളുടെ ഊഴം ഉടൻ വരും.',
    queueProgress: 'ക്യൂ പുരോഗതി',
    tokenGenerated: 'ടോക്കൺ സൃഷ്ടിച്ചു',
    almostYourTurn: 'നിങ്ങളുടെ ഊഴം അടുത്തെത്തി',
    yourTurn: 'നിങ്ങളുടെ ഊഴമായി',
    refreshStatus: 'നില പുതുക്കുക',
    autoRefreshOn: 'ഓട്ടോ-റിഫ്രഷ് സജീവമാണ്',
    patientsWaiting: 'കാത്തിരിക്കുന്ന രോഗികൾ',
    bookDoctorVisit: 'ഡോക്ടറെ കാണാൻ ബുക്ക് ചെയ്യുക',
    step: 'ഘട്ടം',
    selectDoctor: 'ഡോക്ടറെ തിരഞ്ഞെടുക്കുക',
    selectDate: 'തീയതി തിരഞ്ഞെടുക്കുക',
    selectTime: 'സമയം തിരഞ്ഞെടുക്കുക',
    confirmBooking: 'സ്ഥിരീകരിക്കുക',
    continueBtn: 'തുടരുക',
    backBtn: 'പിന്നോട്ട്',
    bookingSuccess: 'അപ്പോയിന്റ്മെന്റ് സ്ഥിരീകരിച്ചു!',
    tokenGeneratedNotice: 'നിങ്ങളുടെ ഡിജിറ്റൽ ടോക്കൺ സൃഷ്ടിക്കപ്പെട്ടു',
    close: 'അടയ്ക്കുക',
    settingsTitle: 'ക്രമീകരണങ്ങളും മുൻഗണനകളും',
    settingsSubtitle: 'ഭാഷ, ശബ്ദം തുടങ്ങിയവ',
    selectLang: 'ആപ്പ് ഭാഷ തിരഞ്ഞെടുക്കുക',
    chooseLangDesc: 'ക്യൂ വിവരങ്ങൾക്ക് നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക:',
    queueAlerts: 'ഓഡിയോ & മുന്നറിയിപ്പ് ക്രമീകരണങ്ങൾ',
    voiceAnnounce: 'ശബ്ദ അറിയിപ്പ്',
    voiceDesc: 'ടോക്കൺ മാറുമ്പോൾ ശബ്ദമുണ്ടാകും',
    smsAlerts: 'എസ്എംഎസ് / വാട്സ്ആപ്പ് അപ്ഡേറ്റുകൾ',
    smsDesc: 'മുന്നിൽ 2 പേരുള്ളപ്പോൾ സന്ദേശം ലഭിക്കും',
    seniorMode: 'ഹൈ കോൺട്രാസ്റ്റ് മോഡ്',
    seniorDesc: 'വലിയ ടോക്കൺ ഡിസ്പ്ലേ',
    emergencyContact: 'അടിയന്തര സഹായം',
    emergency247: '24/7 ലഭ്യമാണ്',
    dialHelp: 'വിളിക്കുക 108 / 911',
    smartQueueSys: 'സ്മാർട്ട് ആശുപത്രി ക്യൂ മാനേജ്മെന്റ് സിസ്റ്റം',
    selectLoginRole: 'ലോഗിൻ റോൾ തിരഞ്ഞെടുക്കുക:',
    loginAs: 'ആയി ലോഗിൻ ചെയ്യുക',
    signUp: 'രജിസ്റ്റർ ചെയ്യുക',
    skipForNow: 'ഇപ്പോൾ ഒഴിവാക്കുക',
    useDemoCredentials: 'ഡെമോ ഉപയോഗിക്കുക',
    orTypeCustom: 'അല്ലെങ്കിൽ ഇമെയിലും പാസ്‌വേഡും നൽകുക',
    onDuty: 'ഡ്യൂട്ടിയിലാണ്',
    todayQueue: 'ഇന്നത്തെ ക്യൂ',
    completedConsultations: 'പൂർത്തിയായവ',
    currentPatient: 'നിലവിലെ രോഗി',
    callNext: 'അടുത്ത രോഗിയെ വിളിക്കുക',
    completeConsultation: 'പരിശോധന പൂർത്തിയാക്കുക',
    hospitalOverview: 'ആശുപത്രി അവലോകനം',
    todayAppointments: 'ഇന്നത്തെ അപ്പോയിന്റ്മെന്റുകൾ',
    avgWait: 'ശരാശരി കാത്തിരിപ്പ് സമയം',
    liveHospitalQueue: 'തത്സമയ ക്യൂ',
  },
};

interface LanguageContextType {
  language: string;
  setLanguage: (code: string) => void;
  currentLanguage: LanguageOption;
  languages: LanguageOption[];
  t: (key: TranslationKey | (string & {}), fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<string>(() => {
    return localStorage.getItem('quickcare_language') || 'en';
  });

  const setLanguage = (code: string) => {
    setLanguageState(code);
    localStorage.setItem('quickcare_language', code);
    
    // Set document direction for RTL languages like Arabic
    const selected = AVAILABLE_LANGUAGES.find(l => l.code === code);
    if (selected?.dir === 'rtl') {
      document.documentElement.dir = 'rtl';
    } else {
      document.documentElement.dir = 'ltr';
    }
  };

  useEffect(() => {
    const selected = AVAILABLE_LANGUAGES.find(l => l.code === language);
    if (selected?.dir === 'rtl') {
      document.documentElement.dir = 'rtl';
    } else {
      document.documentElement.dir = 'ltr';
    }
  }, [language]);

  const currentLanguage =
    AVAILABLE_LANGUAGES.find((l) => l.code === language) || AVAILABLE_LANGUAGES[0];

  const t = (key: TranslationKey | string, fallback?: string): string => {
    const langDict = TRANSLATIONS[language];
    if (langDict && (langDict as Record<string, string>)[key]) {
      return (langDict as Record<string, string>)[key]!;
    }
    // Fallback to English
    const enDict = TRANSLATIONS['en'];
    if (enDict && (enDict as Record<string, string>)[key]) {
      return (enDict as Record<string, string>)[key]!;
    }
    return fallback || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        currentLanguage,
        languages: AVAILABLE_LANGUAGES,
        t,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
